[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EirVS"
authors = [{name = "Phong Lam", email = "phong.lam@icm.uu.se"}]
dynamic = ["version", "description"]
